/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.tads.ads.pi2.view;

import br.senac.sp.tads.ads.pi2.controller.CaixaController;
import br.senac.sp.tads.ads.pi2.controller.ClienteController;
import br.senac.sp.tads.ads.pi2.helper.CaixaHelper;
import br.senac.sp.tads.ads.pi2.helper.ClienteHelper;
import br.senac.sp.tads.ads.pi2.modal.Cliente;
import br.senac.sp.tads.ads.pi2.modal.ProdutoVenda;
import br.senac.sp.tads.ads.pi2.modal.Usuario;
import java.awt.event.KeyEvent;
import static java.lang.String.valueOf;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author victorsantos
 */
public class telaCaixa extends javax.swing.JFrame {

    /**
     * Creates new form telaLivros
     */
    
    private final CaixaController controller;
    private final CaixaHelper helper;
    private Cliente cliente;
    private String pagamento = "";
    private Usuario usuario;
    
    public telaCaixa() throws ClassNotFoundException {
        initComponents();
        // Definindo tamanho in1cial da janela
        //this.setBounds(250, 150, 1124, 718);
        this.setLocationRelativeTo(null);
        pack();
        controller = new CaixaController(this);
        
        controller.getProduto();
        
        this.helper = new CaixaHelper(this);
    }
    
    public telaCaixa(Cliente cliente, Usuario user) throws ClassNotFoundException {
        initComponents();
        // Definindo tamanho in1cial da janela
        //this.setBounds(250, 150, 1124, 718);
        this.setLocationRelativeTo(null);
        pack();
        controller = new CaixaController(this);
        
        controller.getProduto();
        
        this.helper = new CaixaHelper(this);
        
        this.cliente = cliente;
        
        this.txtCliente.setText(cliente.getNome());
        this.usuario = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        panelBusca = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInclusaoProduto = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        lblQtdDisponivel = new javax.swing.JLabel();
        QtdDisponivel = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        panelBusca1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblItensVenda = new javax.swing.JTable();
        btnFinalizarCompra = new javax.swing.JButton();
        txtCliente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        panelBusca2 = new javax.swing.JPanel();
        lblValorAtual = new javax.swing.JLabel();
        panelBusca3 = new javax.swing.JPanel();
        lblQtdItens = new javax.swing.JLabel();
        btnRemoverRegistro = new javax.swing.JButton();
        rdDebito = new javax.swing.JRadioButton();
        rdCredito = new javax.swing.JRadioButton();
        rdDinheiro = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Produto", "Preço", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(35, 70, 72));
        panelPrincipal.setForeground(new java.awt.Color(35, 70, 72));
        panelPrincipal.setToolTipText("");
        panelPrincipal.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                panelPrincipalComponentMoved(evt);
            }
        });

        panelBusca.setBackground(new java.awt.Color(35, 70, 72));
        panelBusca.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Inclusao de Produto", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Produto:");

        txtBusca.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        txtBusca.setForeground(new java.awt.Color(35, 70, 72));
        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscaKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });

        tblInclusaoProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Tipo", "Preco", "Qtd Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInclusaoProduto.setToolTipText("");
        tblInclusaoProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInclusaoProdutoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblInclusaoProduto);
        tblInclusaoProduto.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("*Qtd.:");

        txtQuantidade.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        txtQuantidade.setForeground(new java.awt.Color(35, 70, 72));
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyReleased(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(35, 70, 72));
        btnRegistrar.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setActionCommand("Registrar Item");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblQtdDisponivel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblQtdDisponivel.setForeground(new java.awt.Color(255, 255, 255));
        lblQtdDisponivel.setText("0");

        QtdDisponivel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        QtdDisponivel.setForeground(new java.awt.Color(255, 255, 255));
        QtdDisponivel.setText("Quantidade disponivel: ");

        javax.swing.GroupLayout panelBuscaLayout = new javax.swing.GroupLayout(panelBusca);
        panelBusca.setLayout(panelBuscaLayout);
        panelBuscaLayout.setHorizontalGroup(
            panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscaLayout.createSequentialGroup()
                        .addGap(0, 69, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscaLayout.createSequentialGroup()
                        .addGroup(panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBuscaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(QtdDisponivel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQtdDisponivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBuscaLayout.setVerticalGroup(
            panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscaLayout.createSequentialGroup()
                        .addGroup(panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QtdDisponivel)
                            .addComponent(lblQtdDisponivel)))
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnVoltar.setBackground(new java.awt.Color(35, 70, 72));
        btnVoltar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        panelBusca1.setBackground(new java.awt.Color(35, 70, 72));
        panelBusca1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Venda", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tblItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Codigo", "Nome", "Tipo", "Preço", "Qtd.", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblItensVenda);

        btnFinalizarCompra.setBackground(new java.awt.Color(35, 70, 72));
        btnFinalizarCompra.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        btnFinalizarCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizarCompra.setText("Finalizar Compra");
        btnFinalizarCompra.setActionCommand("Registrar Item");
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });

        txtCliente.setEditable(false);
        txtCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtCliente.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(35, 70, 72));
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cliente: ");

        panelBusca2.setBackground(new java.awt.Color(35, 70, 72));
        panelBusca2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Tota;", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        lblValorAtual.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblValorAtual.setForeground(new java.awt.Color(255, 255, 255));
        lblValorAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorAtual.setText("R$0,00");

        javax.swing.GroupLayout panelBusca2Layout = new javax.swing.GroupLayout(panelBusca2);
        panelBusca2.setLayout(panelBusca2Layout);
        panelBusca2Layout.setHorizontalGroup(
            panelBusca2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusca2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValorAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBusca2Layout.setVerticalGroup(
            panelBusca2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusca2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValorAtual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBusca3.setBackground(new java.awt.Color(35, 70, 72));
        panelBusca3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Qtd. Items", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        lblQtdItens.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblQtdItens.setForeground(new java.awt.Color(255, 255, 255));
        lblQtdItens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtdItens.setText("0");

        javax.swing.GroupLayout panelBusca3Layout = new javax.swing.GroupLayout(panelBusca3);
        panelBusca3.setLayout(panelBusca3Layout);
        panelBusca3Layout.setHorizontalGroup(
            panelBusca3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusca3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQtdItens, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBusca3Layout.setVerticalGroup(
            panelBusca3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusca3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQtdItens)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRemoverRegistro.setBackground(new java.awt.Color(35, 70, 72));
        btnRemoverRegistro.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        btnRemoverRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoverRegistro.setText("Remover Registro"); // NOI18N
        btnRemoverRegistro.setActionCommand("Registrar Item");
        btnRemoverRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverRegistroActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdDebito);
        rdDebito.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        rdDebito.setForeground(new java.awt.Color(242, 241, 240));
        rdDebito.setText("Debito");
        rdDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDebitoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdCredito);
        rdCredito.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        rdCredito.setForeground(new java.awt.Color(242, 241, 240));
        rdCredito.setText("Credito");

        buttonGroup1.add(rdDinheiro);
        rdDinheiro.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        rdDinheiro.setForeground(new java.awt.Color(242, 241, 240));
        rdDinheiro.setText("Dinheiro");
        rdDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDinheiroActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Pagamento: ");

        javax.swing.GroupLayout panelBusca1Layout = new javax.swing.GroupLayout(panelBusca1);
        panelBusca1.setLayout(panelBusca1Layout);
        panelBusca1Layout.setHorizontalGroup(
            panelBusca1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusca1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBusca1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBusca1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCliente))
                    .addGroup(panelBusca1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBusca1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBusca1Layout.createSequentialGroup()
                                .addComponent(rdDebito)
                                .addGap(18, 18, 18)
                                .addComponent(rdCredito)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelBusca1Layout.createSequentialGroup()
                                .addComponent(rdDinheiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(btnFinalizarCompra))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusca1Layout.createSequentialGroup()
                        .addComponent(panelBusca2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelBusca3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusca1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRemoverRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBusca1Layout.setVerticalGroup(
            panelBusca1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusca1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelBusca1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBusca3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBusca2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoverRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBusca1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBusca1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(rdDebito)
                    .addComponent(rdCredito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdDinheiro)
                .addGap(5, 5, 5)
                .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Caixa__dePapel.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jLabel2.setMinimumSize(new java.awt.Dimension(300, 100));
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 100));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(panelBusca1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelBusca1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1124, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelPrincipalComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelPrincipalComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panelPrincipalComponentMoved

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String msg = null;
      
        if(!txtQuantidade.getText().equals("")){
            try {
                if(helper.verificaEstoque()){
                    ProdutoVenda pv = helper.getProdutoVenda();
                    
                    controller.addItemVenda(pv);
                    
                    
                    // continua
                } else{
                    JOptionPane.showMessageDialog(null, "Só esta disponivel "+lblQtdDisponivel.getText()+" unidades deste item!", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            } catch (NumberFormatException e){
                if (msg == null) msg = "Quantidade precisa ser um numero inteiro";
                else msg += "\nQuantidade precisa ser um numero inteiro";
                txtQuantidade.setText("");
            }
        } else{
            msg = "Você precisa preencher o campo de quantidade!";
        }
        
        if(msg != null) JOptionPane.showMessageDialog(this, msg);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        telaCaixa.this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        // Validacao das entradas para finalizacao das compras        
        if (rdDebito.isSelected()){
            pagamento = "Debito";
        } else if (rdCredito.isSelected()) {
            pagamento = "Credito";
        } else if (rdDinheiro.isSelected()) {
            pagamento = "Dinheiro";
        } else {
            JOptionPane.showMessageDialog(this, "Voce deve selecionar um metodo de pagamento!", "Aviso",JOptionPane.WARNING_MESSAGE);
        }
        
        if(!pagamento.equals("")){
            if (!txtCliente.getText().equals("")){
                
                try {
                    controller.createVenda(usuario.getId(), cliente.getId());
                    
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(telaCaixa.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else{
                JOptionPane.showMessageDialog(this, "Voce deve selecionar um Cliente", "Aviso",JOptionPane.WARNING_MESSAGE);
            }
        }
        
                
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnRemoverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverRegistroActionPerformed
        // TODO add your handling code here:
        controller.removeItemVenda();
    }//GEN-LAST:event_btnRemoverRegistroActionPerformed

    private void rdDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDebitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdDebitoActionPerformed

    private void rdDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdDinheiroActionPerformed

    private void txtQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyTyped
        // Validação de entrada quantidade
        char c = evt.getKeyChar();
        
        if(((c < '0') || (c > '9') && (c != KeyEvent.VK_BACK_SPACE))) evt.consume(); 
        
        try {
            Integer.parseInt(valueOf(c));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Neste campo deve ser inserido um numero!", "Aviso", JOptionPane.WARNING_MESSAGE);        
        }
    }//GEN-LAST:event_txtQuantidadeKeyTyped

    private void txtQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeKeyReleased

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtQuantidadeKeyPressed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void txtBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyTyped
        // TODO Quando a tecla é pressionada, trazer os produtos cujo nome ou codigo iniciem com conteudo deste campo
        
    }//GEN-LAST:event_txtBuscaKeyTyped

    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyReleased
        try {
            // TODO add your handling code here:
            controller.getProduto();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(telaCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_txtBuscaKeyReleased

    private void tblInclusaoProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInclusaoProdutoMouseClicked
        // TODO add your handling code here:
        lblQtdDisponivel.setText(tblInclusaoProduto.getValueAt(tblInclusaoProduto.getSelectedRow(), 4).toString());
            
        
        

        
    }//GEN-LAST:event_tblInclusaoProdutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new telaCaixa().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(telaCaixa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public static boolean isNumeric (String n) {
        try {
            Double.parseDouble (n); 
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public JTable getTblInclusaoProduto() {
        return tblInclusaoProduto;
    }

    public JTextField getTxtBusca() {
        return txtBusca;
    }

    public JTextField getTxtQuantidade() {
        return txtQuantidade;
    }

    public JLabel getLblQtdDisponivel() {
        return lblQtdDisponivel;
    }
    
    public JTable getTblItensVenda(){
        return tblItensVenda;
    }

    public JLabel getLblQtdItens() {
        return lblQtdItens;
    }

    public JLabel getLblValorAtual() {
        return lblValorAtual;
    }

    public JButton getBtnRemoverRegistro() {
        return btnRemoverRegistro;
    }
    
    public String getMetodoPagamento(){
        return pagamento;
    }
    
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QtdDisponivel;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRemoverRegistro;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblQtdDisponivel;
    private javax.swing.JLabel lblQtdItens;
    private javax.swing.JLabel lblValorAtual;
    private javax.swing.JPanel panelBusca;
    private javax.swing.JPanel panelBusca1;
    private javax.swing.JPanel panelBusca2;
    private javax.swing.JPanel panelBusca3;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton rdCredito;
    private javax.swing.JRadioButton rdDebito;
    private javax.swing.JRadioButton rdDinheiro;
    private javax.swing.JTable tblInclusaoProduto;
    private javax.swing.JTable tblItensVenda;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
